import { Form } from "@web3uikit/core";
import Head from "next/head";
import { useAddress } from "@thirdweb-dev/react";
import { useState } from "react";
const createNFT = () => {
  const address = useAddress();
  const [image, setImage] = useState(false);
  const submitNFT = (form) => {
    console.log("nft submitted");

    if (form.data[2].inputResult == "") {
      alert("No image found for NFT");
      return;
    }

    const nftName = form.data[0].inputResult;
    const nftDescription = form.data[1].inputResult;
    const nftImage = form.data[2].inputResult;

    console.log(nftName);
    console.log(nftDescription);
    console.log(nftImage);
  };
  return (
    <>
      <Head>
        <title>Cryptoket</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className="flex flex-row justify-center items-center py-3">
        <div className="w-64 border-solid border-2 h-64 mr-2">Image</div>
        <div className="flex flex-col h-64 justify-start items-center ">
          <TextField
            id="outlined-basic"
            label="Name"
            variant="outlined"
            className="mb-3 w-64"
          />
          <TextField
            id="outlined-multiline-static"
            label="Description"
            multiline
            rows={4}
            className="w-64 "
          />

          <button className="w-64 rounded-lg bg-indigo-700 text-white mt-2 py-2 px-4 hover:bg-indigo-900 ">
            Create
          </button>
        </div>
      </div> */}
      {address ? (
        <div className="flex flex-auto h-screen justify-center -mt-1 py-4 items-start bg-gradient-to-r from-blue-400 to-emerald-400">
          <Form
            onSubmit={submitNFT}
            buttonConfig={{
              text: "Mint",
              theme: "custom",
              customize: {
                backgroundColor: "#FFC300",
                color: "black",
                fontSize: "14px",
                onHover: "darken",
                padding: "6px 12px",
              },
            }}
            data={[
              {
                name: "Name",
                type: "text",
                inputWidth: "100%",
                value: "",
                key: "nftName",
                validation: {
                  required: true,
                },
              },
              {
                name: "Description",
                type: "text",
                inputWidth: "100%",
                value: "",
                validation: {
                  required: true,
                },
                key: "nftDescription",
              },
              {
                name: "Image",
                type: "file",
                value: "",
                inputWidth: "100%",
                key: "nftImage",
                validation: {
                  required: true,
                },
              },
            ]}
            title="Create an NFT"
            id="createForm"
          ></Form>
        </div>
      ) : (
        <div className="flex flex-auto justify-center">Connect Wallet</div>
      )}
    </>
  );
};

export default createNFT;
