import { Form } from "@web3uikit/core";
import Head from "next/head";
import { useAddress } from "@thirdweb-dev/react";
import { useEffect, useState } from "react";
import useNftMarket from "../hooks/nftMarket";
import NFTMarket from "../constants/NFTMarket.json";
import { useMoralis, useWeb3Contract } from "react-moralis";

const NFT_MARKET_ADDRESS = process.env.NEXT_PUBLIC_NFT_MARKET_ADDRESS;
const PRIVATE_KEY = process.env.NEXT_PUBLIC_PRIVATE_KEY;

const createNFT = () => {
  console.log(PRIVATE_KEY);
  const { chainId, isWeb3Enabled } = useMoralis();
  const address = useAddress();
  const [isLoading, setIsLoading] = useState(false);
  const [mintBtnText, setMintBtnText] = useState("Mint");
  const { createNftTokenUri } = useNftMarket();

  const { runContractFunction } = useWeb3Contract();

  useEffect(() => {}, [isWeb3Enabled]);

  // const nftMarket = new Contract(NFT_MARKET_ADDRESS, NFTMarket.abi, signer);

  const submitNFT = async (form) => {
    console.log("nft submitted");
    setIsLoading(true);
    setMintBtnText("Minting");
    if (form.data[2].inputResult == "") {
      alert("No image found for NFT");
      return;
    }

    const nftName = form.data[0].inputResult;
    const nftDescription = form.data[1].inputResult;
    const nftImage = form.data[2].inputResult;

    const nftValues = {
      name: nftName,
      desc: nftDescription,
      image: nftImage,
    };

    const tokenUri = await createNftTokenUri(nftValues);
    console.log(`Token URI: ${tokenUri}`);

    const params = {
      abi: NFTMarket.abi,
      contractAddress: NFT_MARKET_ADDRESS,
      functionName: "mintNFT",
      params: {
        tokenURI: tokenUri,
      },
    };

    try {
      await runContractFunction({
        params: params,
        onSuccess: async (tx) => {
          setIsLoading(false);
          setMintBtnText("Minted");
          const reciept = await tx.wait();
          console.log(reciept);
        },
        onError: (e) => {
          setIsLoading(false);
          setMintBtnText("Failed");
          console.log(e);
        },
      });
      // const transaction = await nftMarket.mintNFT(tokenUri);
      // const reciept = await transaction.wait();
      // console.log(reciept);
    } catch (e) {
      console.log(e);
    }

    // console.log(nftName);
    // console.log(nftDescription);
    // console.log(nftImage);
  };
  return (
    <>
      <Head>
        <title>Cryptoket</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className="flex flex-row justify-center items-center py-3">
        <div className="w-64 border-solid border-2 h-64 mr-2">Image</div>
        <div className="flex flex-col h-64 justify-start items-center ">
          <TextField
            id="outlined-basic"
            label="Name"
            variant="outlined"
            className="mb-3 w-64"
          />
          <TextField
            id="outlined-multiline-static"
            label="Description"
            multiline
            rows={4}
            className="w-64 "
          />

          <button className="w-64 rounded-lg bg-indigo-700 text-white mt-2 py-2 px-4 hover:bg-indigo-900 ">
            Create
          </button>
        </div>
      </div> */}
      {isWeb3Enabled ? (
        <div className="flex flex-auto h-screen justify-center -mt-1 py-4 items-start bg-gradient-to-r from-blue-400 to-emerald-400">
          <Form
            onSubmit={submitNFT}
            buttonConfig={{
              isLoading: isLoading,
              loadingText: mintBtnText,
              text: mintBtnText,
              theme: "custom",
              customize: {
                backgroundColor: "#FFC300",
                color: "black",
                fontSize: "14px",
                onHover: "darken",
                padding: "6px 12px",
              },
            }}
            data={[
              {
                name: "Name",
                type: "text",
                inputWidth: "100%",
                value: "",
                key: "nftName",
                validation: {
                  required: true,
                },
              },
              {
                name: "Description",
                type: "text",
                inputWidth: "100%",
                value: "",
                validation: {
                  required: true,
                },
                key: "nftDescription",
              },
              {
                name: "Image",
                type: "file",
                value: "",
                inputWidth: "100%",
                key: "nftImage",
                validation: {
                  required: true,
                },
              },
            ]}
            title="Create an NFT"
            id="createForm"
          ></Form>
        </div>
      ) : (
        <div className="flex flex-auto justify-center">Connect Wallet</div>
      )}
    </>
  );
};

export default createNFT;
