import Head from "next/head";
import { useAddress } from "@thirdweb-dev/react";
const Home = () => {
  const address = useAddress();
  return (
    <>
      <Head>
        <title>Cryptoket</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/ape.png" />
      </Head>
      <div>
        {address ? (
          <h1 className="font-mono text-base">Home</h1>
        ) : (
          <h1 className="font-mono text-base">Connect Wallet</h1>
        )}
      </div>
    </>
  );
};

export default Home;
