import Head from "next/head";
const ListNFT = () => {
  return (
    <>
      <Head>
        <title>Cryptoket</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-auto justify-center items-center">
        <h1>List an NFT</h1>
      </div>
    </>
  );
};

export default ListNFT;
