import Head from "next/head";
const OwnedNFT = () => {
  return (
    <>
      <Head>
        <title>Cryptoket</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <h1>Owned NFT Page</h1>
      </div>
    </>
  );
};

export default OwnedNFT;
